### ISSUE TITLE
Menu bar development

### ISSUE THREAD

**Issue by rdoubleaid** [holistic-web/ship-app#3]
### Tasks

>Raaid
- [x] REDESIGN!

See here for a mockup: 
![menu_bar](https://user-images.githubusercontent.com/41013746/42923103-ae021cf2-8b1b-11e8-87c2-0386ef606962.png)

- [x] 'Settings' (gear logo (
![gear](https://user-images.githubusercontent.com/41013746/42922990-2e4fa0f6-8b1b-11e8-9474-ddbcdf2c9231.png)
)) to the FAR LEFT. Cannot be swiped onto. Upon tap, opens basic list with settings options (see Settings Screen Development for further information).
- [x] 'Ship' (logo: ![ship logo transparent](https://user-images.githubusercontent.com/41013746/42920670-cf6e78d8-8b0f-11e8-96ee-5e405fcb6248.png) ) to the CENTRE LEFT. Can be swiped on to and tapped on. Opens swipe page (see Swipe Function Development for further info). Page user sees upon opening app (assuming they are logged in, else login screen is what they'll see upon opening app).
- [x] 'Messaging' (standard envelope logo (
![envelope](https://user-images.githubusercontent.com/41013746/42923001-36d59c26-8b1b-11e8-9ed3-ef6d6e58b189.png)
)) to the CENTRE RIGHT. Can be swiped on to and tapped on. Opens messaging page (see Messaging Functionality development for fruther info). Has notifications - to the left of the logo, in purple, Ship chat notifications; to the right of the logo, in red, Match chat notifications.
- [x] 'Crush' (magnifying glass logo (
![search](https://user-images.githubusercontent.com/41013746/42923019-4de18b78-8b1b-11e8-9d78-c8c01c9718ca.png)
)) to the FAR RIGHT. Cannot be swiped onto. Upon tap, opens Search pop-up (see Crush Function Development for necessary information).

- use the same rules for notifications as in the last implementation.

### Questions
- [x] can you explain how this menu item to page mapping works? It seems counter-intuitive to have menu items be inconsistent in where they take you

### Answer
fair point. Forget the last sentence of each point.

### Features
- notification counts are displayed if greater than 0
- notification counts are red if notifications have have arrived since last time they were checked
- each icon triggers a unique function that will navigate to a screen through whatever logic we choose

>Raaid
- [x] Fishing rod in the middle with, if >1, a small number in a circle to the top right indicating number of new Match chat messages. If 0, no small number in a circle, just the logo. Tap to open messages if >1. Tap to go on corresponding page if 0.
- [x] Ship logo TO THE RIGHT with, if >1, a small number in a circle to the top right indicating number of new Ship chat messages. If 0, no small number in a circle, just the logo. Tap to open messages if >1. Tap to go on corresponding page if 0.
- [x] Magnifying glass to the left to open Crush page

**Comment by rdoubleaid** [comment]
![menu bar](https://user-images.githubusercontent.com/41013746/42538072-b586ad14-848e-11e8-9310-7e0cadece9ca.PNG)

**Comment by michaelfitzhavey** [comment]
<img width="416" alt="screen shot 2018-07-17 at 05 58 36" src="https://user-images.githubusercontent.com/2746248/42797563-b4079aea-8987-11e8-8ce0-2609ecfa3340.png">

**Comment by michaelfitzhavey** [comment]
http://ship-app.s3-website.eu-west-2.amazonaws.com/#/
